### ISSUE TITLE
Correct way of setting up output='dataframe'

### ISSUE THREAD

**Issue by slazarov** [gusutabopb/aioinflux#15]
Hello, should the `output` parameter be set during instantiation or afterwards? E.g, the default example yields:

**1)**
```python
import asyncio
from aioinflux import InfluxDBClient

point = {
    'time': '2009-11-10T23:00:00Z',
    'measurement': 'cpu_load_short',
    'tags': {'host': 'server01',
             'region': 'us-west'},
    'fields': {'value': 0.64}
}


async def main():
    client = InfluxDBClient(host='localhost', port=8086, username='root',
                            password='root', db='db')
    client.output = 'dataframe'
    await client.create_database(db='db')
    await client.write(point)
    resp = await client.query('SELECT value FROM cpu_load_short')
    print(resp)
asyncio.get_event_loop().run_until_complete(main())
```  
>> {'results': [{'statement_id': 0, 'series': [{'name': 'cpu_load_short', 'columns': ['time', 'value'], 'values': [[1257894000000000000, 0.64]]}]}]}

**2)**
However, when you set `output` like this, it still yields the same dict as in above and not a dataframe:
```python
client = InfluxDBClient(host='localhost', port=8086, username='root',
                            password='root', db='db' output='dataframe')
```

**3)**
In contrast to that, if you set the parameter on the next line like this:
```python
client = InfluxDBClient(host='localhost', port=8086, username='root',
                            password='root', db='db')
client.output = 'dataframe'
```
Then you successfully get a `Dataframe` as a result, i.e:
```
                           value
2009-11-10 23:00:00+00:00   0.64
```

From debuging the code I saw that the `output` parameter is being overwritten by `async def get_tag_info(self)`. In the docstring you have specified that this method is necessary for the library to correctly parse dataframes. However, if you don't specify the `output` type during the instantiation, then `async def get_tag_info(self)` won't be run. Hence, no correct parsing?

On the other hand, if you specify the parameter during the instantiation and then further overwrite it before querying with `client.output = 'dataframe'`,  then you will get an error like this:

> Task exception was never retrieved
> future: <Task finished coro=<get_tag_info() done, defined at /Python-Projects/Testing/venv/python3/lib/python3.6/site-packages/aioinflux/client.py:327> exception=KeyError('results',)>
> Traceback (most recent call last):
>   File "/Python-Projects/Testing/venv/python3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3063, in get_loc
>     return self._engine.get_loc(key)
>   File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'results'

**Comment by gusutabopb** [comment]
Thanks a lot for the detailed bug report!

I had also noticed some weird responses (dict when dataframe was exepceted, etc) in my production usage of aioinflux, and the cause seems to be this bug.

I am not entirely sure what was causing the bug, but it was definitely something inside the `get_tag_info` (which was a somewhat excessively complex). Since I don't think the functionality for which it existed (to allow conversion of tag columns to categorical dtype) was being used by anyone or made much sense to begin with, I have removed it completely.

The fix is now on master. I will put out a new release in the coming days.
