### ISSUE TITLE
PEP 563 breaks user-defined class schema validation

### ISSUE THREAD

**Issue by cailloumajor** [gusutabopb/aioinflux#32]
### Background
[PEP 563](https://www.python.org/dev/peps/pep-0563/) behavior is available from Python 3.7 (using `from __future__ import annotations`) and will become the default in Python 3.10.

### Description of the problem
Among changes introduced by PEP 563, the type annotations in `__annotations__` attribute of an object are stored in string form. This breaks in the function below because all the tests expect type objects.
https://github.com/gusutabopb/aioinflux/blob/77f9d24f493365356298a1eb904a27ce046cec27/aioinflux/serialization/usertype.py#L57-L67

### Reproduction

- Define a user-defined class, decorated with `lineprotocol()`:
```python
from typing import NamedTuple

import aioinflux


@aioinflux.lineprotocol
class Production(NamedTuple):
    total_line: aioinflux.INT

# Works well as is
```

- Add `from __future__ import annotations` at the top and you get:
`SchemaError: Must have one or more non-empty field-type attributes [~BOOL, ~INT, ~DECIMAL, ~FLOAT, ~STR, ~ENUM]` at import time.

### Possible solution
Using https://docs.python.org/3/library/typing.html#typing.get_type_hints has the same behavior (returns a dict with values as type objects) with or without `from __future__ import annotations`. Furthermore, the autor of PEP 563 [advises to use it](https://www.python.org/dev/peps/pep-0563/#resolving-type-hints-at-runtime).

**Comment by gusutabopb** [comment]
Thanks for the detailed bug report. This is now fixed and in master. Should be out in a new release soon.

**Comment by gusutabopb** [comment]
As a side note, to test this I had to manually add `from __future__ import annotations` to `tests/test_usertype.py` and debug. However, I can't commit that because it'd break tests in Python 3.6.
